<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $this->db->disableForeignKeyChecks();
        $this->db->table('product')->truncate();
        $this->db->enableForeignKeyChecks();

        $now = date('Y-m-d H:i:s');

        $products = [
            // Category 1: Kue Kering
            [
                'product_image'          => 'choco_hazelnut.jpg',
                'product_name'           => 'Choco Hazelnut Crumb',
                'product_desc'           => 'Kue kering renyah dengan balutan cokelat hazelnut manis dan taburan crumb gurih.',
                'product_price'          => 58000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'choco-hazelnut-crumb',
                'category_id'            => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'nastar_keju.jpg',
                'product_name'           => 'Nastar Keju Premium',
                'product_desc'           => 'Nastar lembut bertabur keju edam dengan isian selai nanas asli buatan sendiri.',
                'product_price'          => 65000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'nastar-keju-premium',
                'category_id'            => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'kastengel.jpg',
                'product_name'           => 'Kastengel Wijsman',
                'product_desc'           => 'Kue keju kaya mentega Wijsman yang gurih, renyah, dan lumer di mulut.',
                'product_price'          => 75000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'kastengel-wijsman',
                'category_id'            => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'putri_salju.jpg',
                'product_name'           => 'Putri Salju Lumer',
                'product_desc'           => 'Kue putri salju berbahan dasar kacang mede dengan balutan gula halus lembut.',
                'product_price'          => 55000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'putri-salju-lumer',
                'category_id'            => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'sagoo_keju.jpg',
                'product_name'           => 'Sagoo Keju Renyah',
                'product_desc'           => 'Kue sagu keju khas Indonesia yang sangat lumer dan harum aroma santan & keju.',
                'product_price'          => 50000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'sagoo-keju-renyah',
                'category_id'            => 1,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],

            // Category 2: Kue Basah
            [
                'product_image'          => 'lapis_legit.jpg',
                'product_name'           => 'Lapis Legit Roll',
                'product_desc'           => 'Kue lapis legit gulung istimewa beraroma spekkoek khas resep legendaris.',
                'product_price'          => 120000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'lapis-legit-roll',
                'category_id'            => 2,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'risoles.jpg',
                'product_name'           => 'Risoles Ragout Ayam',
                'product_desc'           => 'Risoles goreng renyah isi ragout ayam creamy dan sayuran segar.',
                'product_price'          => 35000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'risoles-ragout-ayam',
                'category_id'            => 2,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'klepon.jpg',
                'product_name'           => 'Klepon Molen Special',
                'product_desc'           => 'Kue tradisional klepon dengan lelehan gula merah asli dan parutan kelapa.',
                'product_price'          => 40000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'klepon-molen-special',
                'category_id'            => 2,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'bolu_kukus.jpg',
                'product_name'           => 'Bolu Kukus Mekar',
                'product_desc'           => 'Bolu kukus mekar warna-warni yang sangat lembut dan manisnya pas.',
                'product_price'          => 30000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'bolu-kukus-mekar',
                'category_id'            => 2,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'dadar_gulung.jpg',
                'product_name'           => 'Dadar Gulung Unti',
                'product_desc'           => 'Dadar gulung pandan hijau alami dengan isian unti kelapa manis.',
                'product_price'          => 32000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'dadar-gulung-unti',
                'category_id'            => 2,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],

            // Category 3: Hampers
            [
                'product_image'          => 'hampers_exclusive.jpg',
                'product_name'           => 'Exclusive Celebration Gift Box',
                'product_desc'           => 'Paket hampers mewah berisi 4 toples kue kering pilihan dan kartu ucapan.',
                'product_price'          => 350000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'exclusive-celebration-gift-box',
                'category_id'            => 3,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'hampers_sweet.jpg',
                'product_name'           => 'Sweet Moments Hampers',
                'product_desc'           => 'Hampers manis dengan kombinasi cookies artisan dan kue kering favorit.',
                'product_price'          => 280000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'sweet-moments-hampers',
                'category_id'            => 3,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'hampers_royal.jpg',
                'product_name'           => 'Royal Delights Package',
                'product_desc'           => 'Paket hampers komplit 6 jenis kue pilihan Jeikinan Cake untuk momen istimewa.',
                'product_price'          => 450000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'royal-delights-package',
                'category_id'            => 3,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'hampers_mini.jpg',
                'product_name'           => 'Mini Celebration Hampers',
                'product_desc'           => 'Hampers kemasan ekonomis nan elegan berisi 2 toples kue kering pilihan.',
                'product_price'          => 195000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'mini-celebration-hampers',
                'category_id'            => 3,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],

            // Category 4: Cake
            [
                'product_image'          => 'chocolate_fudge.jpg',
                'product_name'           => 'Chocolate Fudge Cake',
                'product_desc'           => 'Kue cokelat lezat berlapis fudge cokelat pekat khas Jeikinan Cake.',
                'product_price'          => 175000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'chocolate-fudge-cake',
                'category_id'            => 4,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'strawberry_shortcake.jpg',
                'product_name'           => 'Strawberry Shortcake',
                'product_desc'           => 'Kue spons dengan potongan buah stroberi segar dan krim lembut pilihan.',
                'product_price'          => 160000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'strawberry-shortcake',
                'category_id'            => 4,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'pandan_chiffon.jpg',
                'product_name'           => 'Pandan Chiffon Cake',
                'product_desc'           => 'Chiffon cake rasa pandan suji alami yang sangat empuk dan wangi.',
                'product_price'          => 85000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'pandan-chiffon-cake',
                'category_id'            => 4,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'red_velvet.jpg',
                'product_name'           => 'Red Velvet Cream Cheese',
                'product_desc'           => 'Red velvet cake klasik bertekstur lembut dengan lapisan cream cheese gurih.',
                'product_price'          => 190000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'red-velvet-cream-cheese',
                'category_id'            => 4,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'tiramisu.jpg',
                'product_name'           => 'Tiramisu Supreme Cake',
                'product_desc'           => 'Tiramisu cake lembut beraroma kopi espres murni dan keju mascarpone mewah.',
                'product_price'          => 185000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'tiramisu-supreme-cake',
                'category_id'            => 4,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],

            // Category 5: Cookie
            [
                'product_image'          => 'double_choco.jpg',
                'product_name'           => 'Double Choco Chip Cookies',
                'product_desc'           => 'Soft cookies cokelat pekat bertabur chocolate chips melimpah.',
                'product_price'          => 48000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'double-choco-chip-cookies',
                'category_id'            => 5,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'matcha_almond.jpg',
                'product_name'           => 'Matcha Almond Cookies',
                'product_desc'           => 'Cookies rasa teh hijau matcha jepang dengan irisan kacang almond renyah.',
                'product_price'          => 52000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'matcha-almond-cookies',
                'category_id'            => 5,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'red_velvet_cookie.jpg',
                'product_name'           => 'Red Velvet Crunch Cookies',
                'product_desc'           => 'Cookies rasa red velvet dengan lelehan putih cokelat di bagian dalam.',
                'product_price'          => 50000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'red-velvet-crunch-cookies',
                'category_id'            => 5,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'oatmeal_raisin.jpg',
                'product_name'           => 'Oatmeal Raisin Cookies',
                'product_desc'           => 'Cookies gandum sehat berserat tinggi dengan kismis manis nan legit.',
                'product_price'          => 45000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 0,
                'product_slug'           => 'oatmeal-raisin-cookies',
                'category_id'            => 5,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
            [
                'product_image'          => 'biscoff_cookies.jpg',
                'product_name'           => 'Lotus Biscoff Cookies',
                'product_desc'           => 'Cookies kekinian berbahan biskuit dan selai Lotus Biscoff rasa karamel unik.',
                'product_price'          => 55000.00,
                'product_is_available'   => 1,
                'product_is_best_seller' => 1,
                'product_slug'           => 'lotus-biscoff-cookies',
                'category_id'            => 5,
                'created_at'             => $now,
                'updated_at'             => $now,
            ],
        ];

        $this->db->table('product')->insertBatch($products);
    }
}
